#!/usr/bin/env bash

#change directory
# install vundle

echo "Installing Vundle"
mkdir -p ~/.vim/bundle
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

# get vimrc
echo "Getting .vimrc"
ln -s ~/.dotfiles/.vimrc ~/.vimrc

# install vundle bundles
echo "Installing vundle bundles"
vim +BundleInstall +qall

echo ""
echo ""
